version: '3.8'

services:
  semantic_id_resolver:
    build:
      context: ../../../semantic_id_resolver
    ports:
      - "8125:8015"
    networks:
      - semantic_network
    depends_on:
      - python-semantic-matcher_1
      - python-semantic-matcher_2

  python-semantic-matcher_1:
    # container_name: python-semantic-matcher_1
    build:
      context: ../../../python-semantic-matcher #TODO install via pip in Dockerfile
    ports:
      - "8000:8010"
    networks:
      - semantic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://python-semantic-matcher_1:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  python-semantic-matcher_2:
    # container_name: python-semantic-matcher_2
    build:
      context: ../../../python-semantic-matcher
    ports:
      - "8001:8011"
    networks:
      - semantic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://python-semantic-matcher_2:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-semantic-matcher:
    # command: tail -f /dev/null
    build:
      context: .
    ports:
      - "8100:8019"
    networks:
      - semantic_network
    volumes:
      - ./data:/app/data
      - ../../main:/app/main
      - ../../util:/app/util
      - ../../model:/app/model
    depends_on:
      - python-semantic-matcher_1
      - python-semantic-matcher_2

networks:
  semantic_network:
    driver: bridge
